### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.cheatsheet#11]
Line breaks seem to have dropped out.  Compare, for example, "if/else statement" in the original and marked up versions:

https://github.com/QuantEcon/QuantEcon.cheatsheet/blob/master/index.rst
http://cheatsheets.quantecon.org/

cc @DrDrij

**Comment by DrDrij** [comment]
![image](https://cloud.githubusercontent.com/assets/5886045/18941581/bf9a6f36-8655-11e6-9054-1a58e1b43f9e.png)
CSS updated, line breaks preserved. Pushed to live.
