### ISSUE TITLE
programming section, show python whitespace

### ISSUE THREAD

**Issue by sglyon** [QuantEcon/QuantEcon.cheatsheet#17]
In the programming section we go over basic control flow. The examples are valid/complete in Julia and matlab, but would have an error in python because there is no indented block after the start of the block.

Maybe we split them over 3 lines and do something like this:

``` python
if i <= N:
    # do something
```

``` matlab
if i <= N
    # do something
end
```

``` julia
if i <= N
    # do something
end
```

I don't love that proposal, but I think highlighting the importance of whitespace would be helpful for a matlab programmer trying to use this to start learning python

**Comment by vgregory757** [comment]
The indents are there in the .rst file. They're just not showing up in the html version. It seems like it has something to do with the theme, because they show up in the old version. cc @DrDrij
