### ISSUE TITLE
Talk about numpy import

### ISSUE THREAD

**Issue by sglyon** [QuantEcon/QuantEcon.cheatsheet#18]
Throughout we've assumed that users have run 

``` python
import numpy as np
```

This is canonical, but for a new-comer to python it might throw them off that `np` is not defined. 

Perhaps before the table starts we have a quick note that states this implicit import.

**Comment by jstac** [comment]
+1

We can replace the sentence "This document summarizes commonly-used, equivalent commands across MATLAB, Python, and Julia"  --- which will be redundant once we change the title to "QuantEcon MATLAB - Python - Julia Cheat Sheet" ---  with "The Python code assumes that NumPy is installed and imported as `import numpy as np`."

**Comment by vgregory757** [comment]
Thanks for all these suggestions @spencerlyon2 and @jstac! I'll work on them tomorrow when I am back on my computer.
