### ISSUE TITLE
Add \cdot for Julia

### ISSUE THREAD

**Issue by ChrisRackauckas** [QuantEcon/QuantEcon.cheatsheet#22]
For Julia you can use the unicode \cdot for `dot(A,B)`. It's a nice alternative that should be shown.

**Comment by sglyon** [comment]
Hey @ChrisRackauckas thanks for following along here.

I think this suggestion would fit well in the Julia only cheatsheet that @vgregory757 has been working on. 

The purpose of the Matlab-Python-Julia cheatsheet is not to show _all_ the ways to do certain operations, but rather make it convenient for someone who knows one of those languages to get a jump start on learning the other. I think showing unicode operators goes a bit beyond that purpose as it requires extra editor setup for people to do that outside the REPL or notebook.

**Comment by ChrisRackauckas** [comment]
It only requires extra editor setup outside of the REPL, notebooks, or Juno. I'd call that pretty standard. It does show how beautiful unicode is as well. Making Julia use `dot` is just bringing it down to their level. But I see what you mean. I hope the Julia-only cheatsheet shows all the nice unicode.

**Comment by ChrisRackauckas** [comment]
I think that with the `RowVector` changes you should add that `A'B` is probably the easiest and most obvious way to take the dot product.

**Comment by arnavs** [comment]
Incorporated in the new cheatsheet. Only took us two years.
