### ISSUE TITLE
.rst versions of the Julia- and Python-specific cheatsheets

### ISSUE THREAD

**Issue by vgregory757** [QuantEcon/QuantEcon.cheatsheet#23]
We would like to have web versions of these: [Julia cheatsheet](https://github.com/QuantEcon/QuantEcon.cheatsheet/tree/master/julia) and [Python cheatsheet](https://github.com/QuantEcon/QuantEcon.cheatsheet/tree/master/python). The plan is to make .rst versions with tables so that we can create them using Sphinx, similar to the main cheatsheet. I tried converting the .tex files to .rst using pandoc, but the tables don't carry over nicely. Maybe some tweaking needs to be done with the .tex tables to get this to work. Any help here would be appreciated!

**Comment by jstac** [comment]
I wonder if it wouldn't be easiest just to write a little Python script to extract the data from the tex files and build the rst tables...

**Comment by mmcky** [comment]
Looking into this -- given the heavy use of non-default LaTeX (i.e. minted) we are asking a lot of `pandoc` here.  I actually think the most efficient solution here is to rework by hand into rst tables. I will start work on the `python` conversion soon.

**Comment by mmcky** [comment]
This issue can be closed. Migrated to `rst` files is done.
