### ISSUE TITLE
python cheatsheet rendering issues

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.cheatsheet#24]
Currently the table format is not rendering correctly for ``python/python-cheatsheet.rst``

**Comment by vgregory757** [comment]
My guess is that it has something to do with the Sphinx theme. I compared the .rst of the original cheatsheet with the resulting html. It seems like in a table, the theme is mapping anything that goes in the first column as a subsection header (the test in bold black font). Then the table columns that appear in the html start from the 2nd column on.

We can probably work with this in the meantime for the Python and Julia specific sheets, but I think they will need to use a different theme.

**Comment by mmcky** [comment]
Thanks @vgregory757. I see what your saying with the subsection header. @DrDrij can we look at setting up a theme for the `python` and `julia` cheat sheets. It might be best if they have a more traditional table layout.

**Comment by mmcky** [comment]
To apply a new style to the `python` and `julia` cheatsheets we need to encode the html with an separate id. This can be done using a sphinx container such as:

```
 .. container:: simple-table

    This is test table

    +---+---------+
    | t | ajkdfjd |
    +===+=========+
    | a | kdjfkjs |
    +---+---------+           

    end test table
```

**Comment by mmcky** [comment]
Added containers to rst files. @DrDrij is working on restoring mathjax rendering.

**Comment by jstac** [comment]
Can we close this?
