### ISSUE TITLE
Add a Stata -- Python & pandas comparison page

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.cheatsheet#33]
To complement our Matlab -- Python -- Julia page, which is great for general coding and dynamic macro, we could add a Stata -- pandas comparison page.  We could even consider making it a Stata -- pandas -- R comparison.

Such an addition would be useful for the empirical / stats / econometrics crowd.

**Comment by natashawatkins** [comment]
done in #34
