### ISSUE TITLE
add R pygments for cheatsheets

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/QuantEcon.cheatsheet#38]
@DrDrij would you be able to help with this? It would be nice to have highlighting for R on https://cheatsheets.quantecon.org/stats-cheatsheet.html

**Comment by DrDrij** [comment]
@natashawatkins R should be highlighting now using:
.. code-block:: r

**Comment by natashawatkins** [comment]
@DrDrij awesome, looks good! Thanks

**Comment by natashawatkins** [comment]
@mmcky would you know why this hasn't changed on the live site yet? I can see it when I use `make html`
