### ISSUE TITLE
Feedback welcome

### ISSUE THREAD

**Issue by vgregory757** [QuantEcon/QuantEcon.cheatsheet#6]
I'm opening this issue to get some ideas on how to improve the cheatsheet moving forward. I think we have a good first pass right now, but would like to hear any suggestions, whether they are regarding commands to add or formatting or anything else! 

cc'ing @jstac @danielcsaba @spencerlyon2 @cc7768 @mmcky 

One thing I know I want to fix is the formatting of the tables. In the html file, they seem to be a little bit too wide on my laptop. In the case of the latex document, the code blocks run across the column boundaries...

**Comment by jstac** [comment]
Looking good guys, thanks!  The width of the columns in html looks OK to me,  but the left margin is too big and the page is not nicely balanced.  I don't think we need much of a margin in this case.

With the LaTeX, I wonder if the best thing is to get the document to display in landscape mode rather than portrait?

http://tex.stackexchange.com/questions/337/how-to-change-certain-pages-into-landscape-portrait-mode

@mmcky Is there any chance you could add some logic into the `make html` command to get this outcome?  If we agree it's a good idea...

Regarding the html, @DrDrij I've invited you to the list of maintainers.  If you clone this repo you can build the website using sphinx.  Might you be willing to work on this site when you have time, to make it look a bit nicer all round? We can do this together if you like.

Also,  I'd like to get this live at `cheatsheet.quantecon.org`.  Would you be willing to help out with that?

**Comment by cc7768** [comment]
I think the first pass is quite good. It covers all of the commands I can think of someone initially needing.

I submitted a one line change as a PR -- In the solve section the Python code referenced `a` whereas Julia, Matlab, and the description all referenced `A`.

The html tables look ok to me as well.

**Comment by vgregory757** [comment]
Thanks @cc7768!

@jstac There may be some options I can change in the Sphinx configuration file to control the sidebar and the orientation of the pages in the pdf. I'll take a look.

**Comment by vgregory757** [comment]
So it seems like it's really difficult or not possible to control fine details from the configuration file. In the html, I can change the width of the sidebar, but this doesn't solve the problem of all the whitespace on the left. In the latex, I can change all the pages to landscape, but then some tables become too tall to fit on the page.

I think an alternative would be to go in and edit the html and tex files themselves but then anytime you run a build with Sphinx it will overwrite these changes. But maybe someone knows more about this than me.

**Comment by jstac** [comment]
@DrDrij is great at this.  He's the person who made the lecture site look like it does, starting from a basic Sphinx configuration.  Let's see if he can do it.  If he can, we only need to worry about content.

**Comment by DrDrij** [comment]
Working on this now. I'll create a custom Sphinx theme for the cheatsheet.
I notice the content entry in the RST is in table form. This looks easier to maintain than custom HTML snippets around the place.
I will work with the format we have in place and try to fit everything nicely to a standard page width and hopefully some responsive CSS which will make the page sit nicely on mobile devices.
Watch this space...

**Comment by jstac** [comment]
@DrDrij Thanks!  

Also, if you could make what we have live at `cheatsheets.quantecon.org` once you're done that would be super helpful.  (Note `cheatsheets` plural because I think there will eventually be a few of them.)

**Comment by DrDrij** [comment]
Site is live: http://cheatsheets.quantecon.org/ (No cloudfront yet, just hosting from S3 bucket)
I have merged recent changes and pushed the new Sphinx theme to the main branch.

**Comment by DrDrij** [comment]
Just a first pass on the theme. Love to hear feedback. It's also responsive, accessible on a smartphone.

**Comment by sglyon** [comment]
Minor feedback: could we have the background color behind code snippets for matlab be orangish; python yellowish; and Julia either green, red, or purpleish? That would make the background color fit with the logo of each language. 

![screen shot 2016-09-28 at 9 39 24 am](https://cloud.githubusercontent.com/assets/1001948/18915570/77f78c32-855f-11e6-986d-f81b439a61ed.png)

![screen shot 2016-09-28 at 9 39 45 am](https://cloud.githubusercontent.com/assets/1001948/18915586/81789062-855f-11e6-81e4-c9a4a7b18e99.png)

![screen shot 2016-09-28 at 9 40 02 am](https://cloud.githubusercontent.com/assets/1001948/18915594/8b1ae868-855f-11e6-8534-dadddeae59d4.png)

**Comment by vgregory757** [comment]
Thanks! I think it looks great! Can we also have the logo at the top link to quantecon.org and a menu at the top so that people can jump down to the category they want?

**Comment by jstac** [comment]
+1 for these requests, and I think we should also change the title to "QuantEcon MATLAB--Python--Julia Cheat Sheet".  As @thomassargent30 mentioned, we will add two additional cheat sheets: one for Python (for those learning Python who don't know another language) and a similar one for Julia.

**Comment by jstac** [comment]
And perhaps a GitHub symbol / link to the GitHub repo somewhere on the top right...

**Comment by jstac** [comment]
And perhaps a GitHub symbol / link to the GitHub repo somewhere on the top right...

**Comment by DrDrij** [comment]
- Code highlight colors updated to match language logos
- Logo links to QuantEcon
- Navigation menu to jump to sections
- Title updated
- GitHub logo added

**Comment by mmcky** [comment]
Thanks @vgregory757. I think this issue can now be closed. If you agree -- please go ahead and close it.
