### ISSUE TITLE
Second cheat sheet

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.cheatsheet#7]
Hi all,

@vgregory757 @mmcky @spencerlyon2 @cc7768 @thomassargent30 

Tom has suggested that we also have a cheat sheet that's more suitable for someone who is learning Python without any programming experience, rather than just a Matlab-Python-Julia translator.  This seems like a good idea.  

We can also look to do the same for Julia --- there will be economies of scale.

@mmcky I know that you started a Python cheat sheet with Zhen and Tom.  Would you mind to drop the source files into a separate folder?  

If any RAs are willing to invest hours in this we'll be happy to fund it.

**Comment by vgregory757** [comment]
I added a Julia version. Let me know if anyone has any feedback/suggestions!

**Comment by jstac** [comment]
Thanks, that's great!

It's very nicely put together.

Semi trivial comment for your consideration: I like spaces around operators (e.g., `A + B`) and it seems to be the convention in most of the Julia base code and libraries.

**Comment by mmcky** [comment]
I think this issue can now be closed. There is both a ``julia`` and ``python`` language specific cheatsheet available.
