### ISSUE TITLE
The "in-place modification" for MATLAB is wrong

### ISSUE THREAD

**Issue by sg-s** [QuantEcon/QuantEcon.cheatsheet#70]
IN the cheatsheet:

```
function f(out, x)
     out = x.^2
end
x = rand(10)
y = zeros(length(x), 1)
f(y, x)
```

Multiple problems with it:

- This is not valid MATLAB syntax. Running this code snippet throws an error as there are statemnts outside a function
- Even if you did define such a function, MATLAB has no concept of inplace modification. Such a thing isn't possible (without magic like `assignin`)

**Comment by mmcky** [comment]
thanks for reporting this @sg-s. 

Can you post the error you get? I am not a matlab user but from the code it looks like `out` would get assigned inside of the function. In the example wouldn't `y` be assigned the results of `x.^2` inside of the function `f`?

I will check with the team.

**Comment by sg-s** [comment]
If I declare the function in a file, and then run the subsequent commands, absolutely nothing happens, because the function has no return value

There is no way to do "in-place modification" using vanilla functions in MATLAB

**Comment by sg-s** [comment]
maybe whoever wrote this was confused because they omitted the semi-colon in the function, so "out" is printed to the console, but isn't actually assigned to any variable.

**Comment by jlperla** [comment]
Yes, definetely wrong as written.  But I believe the following works:
(see https://blogs.mathworks.com/loren/2007/03/22/in-place-operations-on-data/  and http://www.csc.kth.se/utbildning/kth/kurser/DN2255/ndiff13/matopt.pdf

Create a file:
```
function out = f(out, x)
     out = x.^2;
end
```
Create another file
```
function test()
    x = rand(10,1);
    y = zeros(length(x), 1);
    y = f(y, x);
    y
end
```
Note that you have to use the same parameter name for the input and output, and you have to only call/use from functions rather than top level scripts.

@sg-s  I think it is reasonable in the cheatsheet to say that this is complicated rather than explaining all of that.  It isn't like this is something people use frequently.

**Comment by sg-s** [comment]
Sorry I wasn't being clear.

There's a fundamental difference between what MATLAB calls "in place" and what python and Julia are doing. 

In the example you linked, this is some syntactic sugar to coax MATLAB into doing some optimizations to save memory. But you still have to assign the output of the function to a variable, i.e.:

```
y = f(y,x)
```

and specifically

```
f(y,x);
```

will do nothing.

Unless I'm mistaken, this is conceptiually differnet from what's happening in Julia and python, because this

```
f(x)
```

**can change the value of x in the scope that f is called in**. Right? Am I missing something? And this is not possible in MATLAB

edit: I may be wrong, but isn't this because in python, things are passed around by reference and in MATLAB, things are passed around by value?

edit2: AFAIK the only way to do this sort of thing in MATLAB is if the object that goes into the function inherits from the  handle class

edit3: @jlperla putting the test function in a new file/putting those commands in the test func. does nothing. You can do the same thing from the prompt

**Comment by jlperla** [comment]
> In the example you linked, this is some syntactic sugar to coax MATLAB into doing some optimizations to save memory.
> There's a fundamental difference between what MATLAB calls "in place" and what python and Julia are doing.

Well, I think that is the essence of all in-place operations.  Does it modify the existing memory or not.

The semantics of it in the language are different.  i.e. in matlab you have to go `out = f(out, in)` to hint to the compiler that you want to do it inplace.  Certainly it is inconvenient.

> I may be wrong, but isn't this because in python, things are passed around by reference and in MATLAB, things are passed around by value?

It is more complicated than that.  It passes by reference sometimes for sure (e.g. https://www.mathworks.com/matlabcentral/answers/96960-does-matlab-pass-parameters-using-call-by-value-or-call-by-reference)

> edit3: @jlperla putting the test function in a new file/putting those commands in the test func. does nothing. You can do the same thing from the prompt

I don't think so.  Remember that these are all just hints to the matlab compiler so the same code would work either way.

... but with all of this, I think that these discussions are not worth continuing just for a line in a cheatsheet.  It is sufficiently subtle in matlab that we are better off just linking to something and moving on.  The point of the cheatsheest is to help people currently using matlab patterns transition to julia or python, so if not many people are doing the inplace then it isn't worth the trouble.

**Comment by mmcky** [comment]
Thanks @sg-s and @jlperla. I think the best solution here might be to put `N/A` in the Matlab column. The `python` and `julia` syntax is still useful for others.

**Comment by mmcky** [comment]
I propose the following

https://github.com/QuantEcon/QuantEcon.cheatsheet/pull/71

**Comment by mmcky** [comment]
https://cheatsheets.quantecon.org
